#!/usr/bin/env python3
"""
convert.py — Excel → JS data file converter
============================================
Usage:
    python tools/convert.py resources          # converts resources.xlsx → data/resources.js
    python tools/convert.py datasets           # converts datasets.xlsx  → data/datasets.js
    python tools/convert.py all                # converts all configured sheets

Spreadsheet rules:
    - First row = column headers (exact names defined in SCHEMAS below)
    - One row per record
    - Tags/topics: comma-separated values in a single cell, e.g.  "climate risk, finance, TCFD"
    - Lists (variables, formats, links): see schema comments below
    - Empty cells are allowed; mandatory fields are flagged as warnings
    - Extra columns are silently ignored
"""

import sys
import json
import re
import textwrap
from pathlib import Path
from datetime import datetime

try:
    import pandas as pd
except ImportError:
    sys.exit("pandas is required: pip install pandas openpyxl")

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT        = Path(__file__).parent.parent          # project root
EXCEL_DIR   = Path(__file__).parent / "source-excel"
DATA_DIR    = ROOT / "site" / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# ── Helpers ───────────────────────────────────────────────────────────────────
def split_list(value, sep=","):
    """Turn a comma-separated string into a cleaned list; empty → []."""
    if pd.isna(value) or str(value).strip() == "":
        return []
    return [s.strip() for s in str(value).split(sep) if s.strip()]

def clean_str(value, default=""):
    """Return a stripped string or default if NaN/empty."""
    if pd.isna(value):
        return default
    s = str(value).strip()
    return s if s else default

def parse_links(value):
    """
    Parse one or more links from a cell.
    Accepted formats (pick ONE per spreadsheet, be consistent):
        1. Single URL:         https://example.com
        2. Label|URL pairs, one per line:
               Dataset portal|https://example.com
               API docs|https://api.example.com
    Returns: [{"label": "...", "url": "..."}, ...]
    """
    raw = clean_str(value)
    if not raw:
        return []
    links = []
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        if "|" in line:
            parts = line.split("|", 1)
            links.append({"label": parts[0].strip(), "url": parts[1].strip()})
        else:
            # bare URL — use a default label
            links.append({"label": "Open", "url": line})
    return links

def to_js(const_name, records, source_file):
    """Wrap a list of dicts as a JS const declaration."""
    source  = source_file.name if source_file else "unknown"
    ts      = datetime.now().strftime("%Y-%m-%d %H:%M")
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    return textwrap.dedent(f"""\
        /* AUTO-GENERATED by tools/convert.py — do not edit by hand.
           Source: tools/source-excel/{source}
           Generated: {ts}
           Re-generate: python tools/convert.py {const_name.lower()} */

        const {const_name} = {payload};
    """)

def warn(row_num, field, msg):
    print(f"  ⚠  row {row_num+2}: {field} — {msg}")

# ══════════════════════════════════════════════════════════════════════════════
# SCHEMAS
# Each schema maps Excel column headers → processing logic.
# Add/remove fields here when your spreadsheet changes.
# ══════════════════════════════════════════════════════════════════════════════

def convert_resources(excel_path):
    """
    Expected columns (order doesn't matter):
    ┌─────────────────┬──────────┬───────────────────────────────────────────┐
    │ Column header   │ Required │ Notes                                     │
    ├─────────────────┼──────────┼───────────────────────────────────────────┤
    │ type            │ YES      │ article | report | guideline | tool |     │
    │                 │          │ video | podcast                           │
    │ title           │ YES      │ Free text                                 │
    │ author          │ no       │ Author name or institution                │
    │ year            │ no       │ Publication year, e.g. 2023               │
    │ language        │ no       │ ISO code: EN, FR, DE, ES, IT, PT, ZH,    │
    │                 │          │ AR, or "Multi" for multilingual           │
    │ region          │ no       │ Comma-separated geographic scope,         │
    │                 │          │ e.g. "Global", "Europe, Africa"           │
    │ license         │ no       │ e.g. "Open Access", "Restricted"          │
    │ url             │ no       │ Single URL                                │
    │ description     │ no       │ Free text, can be long                    │
    │ tags            │ no       │ Comma-separated, e.g. "climate, finance"  │
    └─────────────────┴──────────┴───────────────────────────────────────────┘

    Optional extra columns (ignored by default — add handling below if needed):
      year, doi, language, region, notes
    """
    VALID_TYPES = {"article", "report", "guideline", "tool", "video", "podcast"}
    df = pd.read_excel(excel_path, sheet_name=0, dtype=str)
    df.columns = [c.strip().lower() for c in df.columns]

    records = []
    for i, row in df.iterrows():
        # ── Mandatory fields ──────────────────────────────
        rtype = clean_str(row.get("type", "")).lower()
        title = clean_str(row.get("title", ""))
        if not title:
            warn(i, "title", "missing — row skipped")
            continue
        if not rtype:
            warn(i, "type", "missing — defaulting to 'article'")
            rtype = "article"
        elif rtype not in VALID_TYPES:
            warn(i, "type", f"'{rtype}' not in {VALID_TYPES} — kept as-is")

        # ── Optional fields ───────────────────────────────
        record = {
            "id":          f"r{str(i+1).zfill(3)}",
            "type":        rtype,
            "title":       title,
            "author":      clean_str(row.get("author", "")),
            "year":        clean_str(row.get("year", "")),
            "language":    clean_str(row.get("language", "")),
            "region":      split_list(row.get("region", "")),
            "license":     clean_str(row.get("license", "")),
            "url":         clean_str(row.get("url", "")),
            "description": clean_str(row.get("description", "")),
            "tags":        split_list(row.get("tags", "")),
        }

        # ── Optional extra columns (uncomment to enable) ──
        # record["year"]     = clean_str(row.get("year", ""))
        # record["doi"]      = clean_str(row.get("doi", ""))
        # record["language"] = clean_str(row.get("language", "EN"))
        # record["region"]   = split_list(row.get("region", ""))

        records.append(record)

    return records


def convert_datasets(excel_path):
    """
    Expected columns:
    ┌──────────────────┬──────────┬──────────────────────────────────────────┐
    │ Column header    │ Required │ Notes                                    │
    ├──────────────────┼──────────┼──────────────────────────────────────────┤
    │ title            │ YES      │ Dataset name                             │
    │ type             │ no       │ Short data type label                    │
    │ provider         │ no       │ Organisation / author                    │
    │ formats          │ no       │ Comma-separated: "GIS, Raster, CSV"      │
    │ coverage         │ no       │ e.g. "Global", "Europe"                  │
    │ temporal         │ no       │ e.g. "1940 – present"                    │
    │ access           │ no       │ "Open Access" | "Request required"       │
    │ description      │ no       │ Free text                                │
    │ variables        │ no       │ Comma-separated variable names           │
    │ tags             │ no       │ Comma-separated topics                   │
    │ links            │ no       │ One URL per line, or Label|URL per line  │
    └──────────────────┴──────────┴──────────────────────────────────────────┘
    """
    df = pd.read_excel(excel_path, sheet_name=0, dtype=str)
    df.columns = [c.strip().lower() for c in df.columns]

    records = []
    for i, row in df.iterrows():
        title = clean_str(row.get("title", ""))
        if not title:
            warn(i, "title", "missing — row skipped")
            continue

        slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
        record = {
            "id":          slug[:40],
            "title":       title,
            "type":        clean_str(row.get("type", "")),
            "provider":    clean_str(row.get("provider", "")),
            "formats":     split_list(row.get("formats", "")),
            "coverage":    clean_str(row.get("coverage", "")),
            "temporal":    clean_str(row.get("temporal", "")),
            "access":      clean_str(row.get("access", "")),
            "description": clean_str(row.get("description", "")),
            "variables":   split_list(row.get("variables", "")),
            "tags":        split_list(row.get("tags", "")),
            "links":       parse_links(row.get("links", "")),
        }
        records.append(record)

    return records


# ── Registry ──────────────────────────────────────────────────────────────────
# Add new sections here: "cli-name": (converter_fn, "ExcelFile.xlsx", "JS_CONST_NAME")
CONVERTERS = {
    "resources": (convert_resources, "resources.xlsx",  "RESOURCES"),
    "datasets":  (convert_datasets,  "datasets.xlsx",   "DATASETS"),
    # "risk":    (convert_risk,      "risk-steps.xlsx", "RISK_STEPS"),  # future
}


def run(target):
    if target not in CONVERTERS:
        sys.exit(f"Unknown target '{target}'. Available: {', '.join(CONVERTERS)}")

    fn, filename, const_name = CONVERTERS[target]
    excel_path = EXCEL_DIR / filename

    if not excel_path.exists():
        sys.exit(f"File not found: {excel_path}\nPlace your Excel file there and retry.")

    print(f"\nConverting {filename} → data/{target}.js …")
    records = fn(excel_path)
    print(f"  ✓  {len(records)} records processed")

    out_path = DATA_DIR / f"{target}.js"
    out_path.write_text(to_js(const_name, records, excel_path), encoding="utf-8")
    print(f"  ✓  Written: {out_path}\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    target = sys.argv[1].lower()
    if target == "all":
        for name in CONVERTERS:
            run(name)
    else:
        run(target)
